export const projects = [
  {
    title: 'Click-app',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/chat-app.jpg',
    tags: ['Sanity', 'O-auth', 'React-dom', 'TailwindCss'],
    source: 'https://google.com',
    visit: 'https://clickappbeta.netlify.app/',
    id: 0,
    icon:'/images/ChatsCircle.png',
    background: 'linear-gradient(119.24deg, #FFFFFF -7.64%, #5DDDE7 16.16%, #1BCCDA 40.55%, #0FC6D5 69.57%, #00ACB9 103.82%);',
  },
  {
    title: 'Blog app',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/blog-app.jpg',
    tags: ['Next Js', 'GraphCMS', 'GraphQL', 'Tailwind CSS'],
    source: 'https://google.com',
    visit: 'https://github.com/Beta-test-initiation/Blog-app',
    id: 1,
    icon:'/images/NewspaperClipping.png',
    background: 'linear-gradient(119.47deg, #FFFFFF -8.88%, #DED7E4 21.06%, #D3C9DC 60.4%, #D0C1DC 103.85%);',
  },
  {
    title: 'Crypto Tracker',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/crypto-app.jpg',
      tags: ['React', 'Redux', 'Ant-design'],
    source: 'https://google.com',
    visit: 'https://github.com/Beta-test-initiation/Crypto-app',
    id: 2,
    icon:'/images/CurrencyBtc.png',
    background: ' linear-gradient(121.69deg, #FFFFFF -14.82%, #C0C0E3 -2.84%, #8282CA 13.61%, #6969B3 43.66%, #6464AD 68.92%, #4E4EA4 94.98%);',
  },
  {
    title: 'Real Estate Finder',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/real-estate-app.jpg',
    tags: ['React', 'Next JS', 'Chakra-UI'],
    source: 'https://google.com',
    visit: 'https://github.com/Beta-test-initiation/real-estate-finder',
    id: 3,
    icon:'/images/Buildings.png',
    background: 'linear-gradient(118.78deg, #FFFFFF -12.55%, #DBDF6D 20.7%, #D1D646 52.28%, #C9CE32 103.78%);',
  },
  {
    title: 'Chess',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/chess-app.jpg',
    tags: ['React-dnd', 'Rxjs', 'Firebase', 'React-router-dom'],
    source: 'https://google.com',
    visit: 'https://github.com/Beta-test-initiation/Chess',
    id: 4,
    icon:'/images/GameController.png',
    background: 'linear-gradient(119.24deg, #FFBCC8 -7.64%, #FF5A78 12.81%, #FF4063 33.54%, #F63256 62.61%, #EC2449 103.82%);',
  },
  
];

export const TimeLineData = [
 
  { year: 2019, text: 'Started my journey with Python', },
  { year: 2020, text: 'Interned Online at J.P. Morgan Chase & Co.', },
  { year: 2021, text: 'Beginning of Frontend learning journey, created personal projects', },
  { year: 2022, text: 'Participated in hackathons to polish my skills', },
];
